<?php
session_start();
$mysqli = new mysqli("localhost", "root", "", "dbecomm");

// Check if the user is logged in
if (!isset($_SESSION['username'])) {
    header("Location: login.php");
    exit();
}

// Get the user's username
$username = $_SESSION['username'];

// Fetch the cart data for the current user from the database
$cartQuery = "SELECT c.id, c.product_id, c.quantity, p.name, p.price, p.image, p.category
            FROM tblcart c
            INNER JOIN products p ON c.product_id = p.id
            WHERE c.username = '$username'";
$cartResult = $mysqli->query($cartQuery);

if ($cartResult) {
    $cart = $cartResult->fetch_all(MYSQLI_ASSOC);
} else {
    $cart = array(); // Set an empty array as the default value
}

// Calculate the total price of the order
$totalPrice = 0;
foreach ($cart as $product) {
    $totalPrice += $product['price'] * $product['quantity'];
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Check if the form fields are set
    if (
        isset($_POST['first_name']) && isset($_POST['last_name']) && isset($_POST['address_line1']) &&
        isset($_POST['city']) && isset($_POST['province']) && isset($_POST['zip_code']) &&
        isset($_POST['phone_number'])
    ) {
        // Get the form data
        $firstName = $_POST['first_name'];
        $lastName = $_POST['last_name'];
        $addressLine1 = $_POST['address_line1'];
        $city = $_POST['city'];
        $province = $_POST['province'];
        $zipCode = $_POST['zip_code'];
        $phoneNumber = $_POST['phone_number'];

        // Save the order details in the database
        $insertOrderQuery = "INSERT INTO tblorders (first_name, last_name, address_line1, city, province, zip_code, phone_number, total_price, status)
                            VALUES ('$firstName', '$lastName', '$addressLine1', '$city', '$province', '$zipCode', '$phoneNumber', '$totalPrice', 'pending')";

        // Execute the query to insert the order details
        $result = $mysqli->query($insertOrderQuery);

        if ($result) {
            // Retrieve the order ID generated by the database
            $orderId = $mysqli->insert_id;

            // Save the product details in the order_products table
            foreach ($cart as $product) {
                $productId = $product['product_id'];
                $quantity = $product['quantity'];

                $insertOrderProductsQuery = "INSERT INTO tblorder_products (order_id, product_id, quantity)
                                            VALUES ('$orderId', '$productId', '$quantity')";

                $result = $mysqli->query($insertOrderProductsQuery);

                if (!$result) {
                    // Handle the case when there is an error inserting product details
                    echo "Failed to insert product details into order_products table.";
                    exit();
                }

                // Mark the product as sold and remove it from the products table
                $updateProductQuery = "UPDATE products SET available = 0 WHERE id = '$productId'";
                $result = $mysqli->query($updateProductQuery);

                if (!$result) {
                    // Handle the case when there is an error updating product availability
                    echo "Failed to update product availability.";
                    exit();
                }
            }

            // Order placement and product details insertion successful
            // Clear the cart for the user
            $clearCartQuery = "DELETE FROM tblcart WHERE username = '$username'";
            $clearCartResult = $mysqli->query($clearCartQuery);

            if ($clearCartResult) {
                // Clear the cart successfully
                echo "Order placed successfully! Your order ID is: " . $orderId;

                // Redirect to homepage.php after placing the order
                header("Location: homepage.php");
                exit();
            } else {
                // Handle the case when there is an error clearing the cart
                echo "Failed to clear the cart.";
            }
        }
    }
}

$mysqli->close();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <title>Checkout</title>
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f2f2f2;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #884a39;
            font-size: 24px;
        }

        h2 {
            margin-bottom: 10px;
            color: #884a39;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table th,
        table td {
            padding: 8px;
            border: 1px solid #ccc;
            text-align: left;
        }

        table th {
            background-color: #c38154;
            color: #fff;
            font-weight: bold;
            padding: 10px;
        }

        .order-details,
        .billing-details {
            margin-bottom: 20px;
        }

        .billing-details p {
            margin-bottom: 5px;
        }

        .checkout-form input[type="text"],
        .checkout-form input[type="tel"] {
            width: 80%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
        }

        .checkout-form button {
            padding: 10px 20px;
            background-color: #884a39;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-top: 2%;
        }

        .checkout-form button:hover {
            background-color: #ffc26f;
            color: #884a39;
        }

        .back-link {
            display: inline-block;
            margin-bottom: 10px;
            color: #884a39;
            text-decoration: none;
            font-size: 16px;
        }

        .back-link:hover {
            color: #ffc26f;
        }

    </style>
</head>

<body>
    <div class="container">
       <a class="back-link" href="homepage.php">&lt; Back to Homepage</a>
        <h1>Checkout</h1>
        <div class="order-details">
            <h2>Order Summary</h2>
            <table>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($cart as $product) { ?>
                        <tr>
                            <td><?php echo $product['name']; ?></td>
                            <td><?php echo '₱' . number_format($product['price'], 2); ?></td>
                            <td><?php echo $product['quantity']; ?></td>
                            <td><?php echo '₱' . number_format($product['price'] * $product['quantity'], 2); ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3">Total</td>
                        <td><strong><?php echo '₱' . number_format($totalPrice, 2); ?></strong></td>
                    </tr>

                </tfoot>
            </table>
        </div>
        <div class="billing-details">
            <h2>Billing Details</h2>
            <form class="checkout-form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                <input type="text" name="first_name" placeholder="First Name" required>
                <input type="text" name="last_name" placeholder="Last Name" required>
                <input type="text" name="address_line1" placeholder="Address Line 1" required>
                <input type="text" name="city" placeholder="City" required>
                <input type="text" name="province" placeholder="Province" required>
                <input type="text" name="zip_code" placeholder="Zip Code" required>
                <input type="tel" name="phone_number" placeholder="Phone Number" required><br>
                <button type="submit">Place Order</button>
            </form>
        </div>
    </div>
</body>

</html>
